trigger:
  branches:
    include:
      - main

pool:
  name: Default


steps:

  - script: |
      cd files
      databricks bundle validate
      databricks bundle deploy -t prod
    env:
      DATABRICKS_HOST: $(DATABRICKS_HOST)
      DATABRICKS_TOKEN: $(DATABRICKS_TOKEN)